name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: test in macos
        run: curl -o- https://raw.githubusercontent.com/WingLim/dotfiles/main/install.sh | bash