name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: test in ubuntu
        run: curl -o- https://raw.githubusercontent.com/WingLim/dotfiles/main/install.sh | bash

     
