name: Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: test in ubuntu
        run: bash install.sh

     
